### ISSUE TITLE
[New Sensor]: Add Echo Button Support

### ISSUE THREAD

**Issue by zLeqitEclipse** [custom-components/ble_monitor#1000]
### Sensor Description

Amazon Alexa Echo Button

### Additional information

The Echo Button has been discontinued quite long ago, but their still really great.
Sad thing Amazon actually stopped giving support for them completely and now you can't event create a new routine and set the trigger to an echo button. Only existing ones will continue to work, so the only option is to take matters in the own hands and connect them and manage them manually via BLE.

**Comment by zLeqitEclipse** [comment]
[dump.txt](https://github.com/custom-components/ble_monitor/files/9454029/dump.txt)

**Comment by Ernst79** [comment]
This device requires a connection, which isn’t possible with ble monitor. It’s better to open a request on the home Assistant forum, where the devs are busy building new BLE integration, also with active connections. I’m closing the issue here, as BLE monitor is not capable of setting up connections.
