### ISSUE TITLE
[Bug]: Air Mentor Pro 2 Sensors not updating unless android app is refreshed

### ISSUE THREAD

**Issue by JonScaife** [custom-components/ble_monitor#1038]
### What happened?

Hi
As mentioned on previous issue, the sensors for my air mentor 2 pro don't change value unless I refresh the android app.  This makes me think the app somehow triggers the update or maybe the air mentor sends different data when it isn't being prompted by the app?

**Comment by Ernst79** [comment]
Ok, can you create a log again, in which you enable "report unknown advertisements ..." for this device? In that way, we can check that 
- 1. it receives any data
- 2. the data is parsed correct/incorrect

**Comment by Ernst79** [comment]
Yes, that is the data I need. These are the BLE advertisements that are received. So, we now know that the device does send data and that BLE monitor is receiving data. 

Next step, checking that the above can be parsed (translated to measurement data) or not. Will look into that

**Comment by Ernst79** [comment]
Ok, one step further. One of the messages can be written as (bytes to hex conversion)
`0bff112102670003000435a6`
`0bff1221013d1a2039270032`

1st byte = length = `0b`
2nd byte = manufacturer specific data = `ff`
3rd + 4th byte = company id = `1121` and `1221` 

In BLE monitor, it checks for this company id here (for airmentor)

https://github.com/custom-components/ble_monitor/blob/a34170f1494e3fbccab5b145b11b6c685b45360a/custom_components/ble_monitor/ble_parser/__init__.py#L292

So, we can add `0x1121` and `1221` to that (note that this is reversed in bytes, so `21 11` becomes `11 21`), but we also need to modify the code in airmentor.py. In airmentor.py, it checks the first byte (`11` or `12` in your data), Currently it only parses `21` and `22`, so that is where things go wrong. 

We need to figure out which data is in the code `11` and `12`. I see that the last two bytes of `11` seem to correspond to your last two bytes of the MAC address, note sure about the rest. I will try to find out, have to check where we got the information from in the past.

**Comment by Ernst79** [comment]
Can be helpful if we can’t find the info. I will try to find some documentation first. if that doesn’t work, we can always try to figure it out by ourselves.

will look into it later today

**Comment by JonScaife** [comment]
Not sure what your last comment means, but hoping you're close to or have a fix?

**Comment by Ernst79** [comment]
Yes, I'm close. Looks like your data with 0x12 is the same as we had as 0x21. The result makes sense, I guess

```
'tvoc': 317, 'temperature': 26.88, 'temperature calibrated': 21.18, 'humidity': 63.36, 'aqi': 50, 'air quality': 'good', 'rssi': -52, 'mac': '5448E68F80A5', 'type': 'Air Mentor Pro 2'
```

**Comment by Ernst79** [comment]
And probably the same for 0x11, which is the same as 0x21. 

```
{'co2': 615, 'pm2.5': 3, 'pm10': 4, 'rssi': -52, 'mac': '5448E68F80A5', 'type': 'Air Mentor Pro 2', 'packet': 'no packet id', 'firmware': 'Air Mentor', 'data': True}
```

Not 100% sure about these measurements for co2, pm2.5 and pm10, as I'm not familiar what to expect, but you can check that later. I'll create a new version.

**Comment by Ernst79** [comment]
Can you try with 10.5.3

**Comment by JonScaife** [comment]
I just updated and rebooted and now the values are populating and updating even without the android app running.  Fantastic work - thank you very much!
