### ISSUE TITLE
[Bug]: Interference with built-in Xiaomi BLE

### ISSUE THREAD

**Issue by nschloe** [custom-components/ble_monitor#1077]
### What happened?

I installed ble_monitor to get data from a new temperature sensor, and noticed that subsequently my plant sensors, connected via the built-in [Xiaomi BLE integration](https://www.home-assistant.io/integrations/xiaomi_ble/), hardly report any data at all. When removing the ble_monitor integration, all works as normal.

Is this a known bug?

**Comment by Ernst79** [comment]
Yes, this is a known bug. It has to do with passive vs active scanning, BLE monitor is using passive scanning by default (can be changed), while the HA Bluetooth integration is using active scanning by default (can sometimes be changed, depends on your BLE adapter (firmware)). The problem is that you only have one BLE adapter, and two integrations constantly telling to change the scanning mode from passive to active and vice versa is not going to work. 

Two options to solve this
1. Use two BLE dongles, one for each integration (can be set both in BLE monitor and in the HA Bluetooth integration)
2. use the same type of scanning mode for both integrations. Passive scanning is preferred, as it saves battery of your sensor, but if not possible, use active scanning for both. You can change this on the BLE monitor side in the BLE monitor settings, for the Xiaomi-ble integration, you can change this in the **HA Bluetooth** integration, as it is a system wide setting. Please note that some sensors require  active scanning, like Govee sensors. In that case, use active scanning. (Xiaomi-ble is able to use passive scanning).

**Comment by nschloe** [comment]
Thanks for the reply. I just found [this FAQ](https://github.com/custom-components/ble_monitor/blob/master/docs/faq.md#conflicts-with-other-components-using-the-same-bt-interface) which basically says what you're saying.

**Comment by nschloe** [comment]
> or the Xiaomi-ble integration, you can change this in the HA Bluetooth integration, as it is a system wide setting.

Where exactly do I find this setting?

**Comment by Ernst79** [comment]
![image](https://user-images.githubusercontent.com/24375847/209938288-f3786a15-0038-4617-bee0-98ecbf9d71a2.png)

Just click on configure on the Bluetooth integration tile in the integrations overview

**Comment by nschloe** [comment]
Ah perfect, thank you!
