### ISSUE TITLE
[Bug]: How to add mi scale 2

### ISSUE THREAD

**Issue by phil-schneider** [custom-components/ble_monitor#1125]
### What happened?

Hello,

I am to stupid to integrate my Mi Scale 2 with this addon.
I used esphome in the past and everything was working.
But now I want to integrate it directly without an esp.
How can I do that? 
Thank you very much

### Sensor type

Mi Scale 2

**Comment by Ernst79** [comment]
It should be recognized automatically. I assume you have a working Bluetooth adapter on your HA system?

**Comment by phil-schneider** [comment]
I have a raspi with build in Bluetooth.
Do I need to initiate something?
Or just stand on the scale

**Comment by Ernst79** [comment]
Just step on the scale. Make sure you are within the range of your HA rapberry

**Comment by jant90** [comment]
I have the same issue, this is my only remaining BLE device that I can't get into HA directly. 

I'm using an ESP32 as Bluetooth proxy for HA and the scale isn't detected at all (Mi Body Composition Scale 2, model XMTZC05HM). However, when I add an [ESPHome Miscale sensor](https://esphome.io/components/sensor/xiaomi_miscale.html) to the very same ESP32 I can get readings just fine so the BLE signal reaches the ESP32 just fine. Is it possible that the advertisement data from our scale model isn't recognized by Passive BLE Monitor?

**Comment by jant90** [comment]
@Ernst79 you [requested logs](https://github.com/home-assistant/core/issues/87791#issuecomment-1424486614) to figure out why the scale isn't detected. Let's first rule out that there aren't any errors in my configuration.

I installed BLE Monitor through HACS and enabled it by adding the following to my configuration.yaml and restarting HA (the MAC address is from my scale):
```yaml
ble_monitor:
  bt_interface: "disable"
  devices:
    - mac: 'D0:3E:7D:BD:C0:35'
      report_unknown: True
```
I also tried:
```yaml
ble_monitor:
  report_unknown: Other
```
And I also enabled the logger:
```yaml
logger:
  default: info
  logs:
    custom_components.ble_monitor: info
```
I don't have a Bluetooth adapter but I'm using an ESP32 with [ESPHome Bluetooth Proxy](https://esphome.io/components/bluetooth_proxy.html). I know the proxy is working because I have several BTHome sensors set up natively in HA (so not through BLE Monitor).

Despite those settings, the logs show nothing regarding to BLE advertisements when I step on the scale. And nothing from the BTHome sensors I've already setup in HA either, (with setting `report_unknown: Other`). The only relevant entries in my log are:

```
2023-02-13 17:07:02.117 WARNING (MainThread) [custom_components.ble_monitor.bt_helpers] There are no BT controllers present in the system!
2023-02-13 17:07:02.207 INFO (MainThread) [custom_components.ble_monitor] Available Bluetooth interfaces for BLE monitor: ["Don't use Bluetooth adapter"]
```



Using [this example from the ESPHome docs](https://esphome.io/components/esp32_ble_tracker.html#on-ble-advertise-trigger) I created a BLE advertisement trigger that logs all BLE advertisements for the MAC address of my scale (on the same ESPHome device that I use as Bluetooth Proxy). The log shows many advertisements when I step on the scale:
```
[17:30:55][D][ble_adv:045]: New BLE device
[17:30:55][D][ble_adv:046]:   address: D0:3E:7D:BD:C0:35
[17:30:55][D][ble_adv:047]:   name: MIBFS
[17:30:55][D][ble_adv:048]:   Advertised service UUIDs:
[17:30:55][D][ble_adv:050]:     - 0x181B
[17:30:55][D][ble_adv:052]:   Advertised service data:
[17:30:55][D][ble_adv:054]:     - 0x181B: (length 13)
[17:30:55][D][ble_adv:056]:   Advertised manufacturer data:
[17:30:55][D][ble_adv:058]:     - 0x0157: (length 6)
```

Therefore I get the impression that none of the BLE advertisements from the Bluetooth Proxy reach BLE Monitor and that the issue is not specific to the scale but with my setup/configuration in general.

**Comment by Ernst79** [comment]
I know what is wrong. BLE monitor is **not** using the native Bluetooth integration from HA. It is therefore not able to receive data from ESPhome Bluetooth proxy.

In stead BLE monitor is able to receive data from ESPHome [BLE Gateway](https://github.com/myhomeiot/esphome-components#ble-gateway). This works pretty much the same, it also forwards data from an ESPhome device to BLEmonitor. 

I’m not sure you can run both ESPhome Bluetooth proxy and ESPhome BLE gateway at one device. In the future we will move MiScale to the Xiaomi BLE integration.

**Comment by jant90** [comment]
I was starting to suspect something like that, pretty confusing when you're just adding Bluetooth to HA now, these legacy methods mixed with the new native Bluetooth implementation I mean. But thanks for pointing me in the right direction! :)

Got it working with those instructions, Mi Scale 2 is detected :). Too bad the BLE Gateway can't be combined with the Bluetooth Proxy though, so I'll probably wait till it's added to the Xiaomi-BLE integration instead.

**Comment by Ernst79** [comment]
Yes, I understand it is confusing. That is because we are in the middle of moving things to core HA integrations. Unfortunately my time is limited, but I do what I can. Fulltime job comes first though.
