### ISSUE TITLE
[Bug]: Mijia wireless switch XMWXKG01LM button Last press attribute Display incorrect

### ISSUE THREAD

**Issue by w961471797** [custom-components/ble_monitor#1327]
### What happened?

Whether pressed or not, it is displayed as single press
<img width="568" alt="59d343f84f5d90eccd35133a070c5fd" src="https://github.com/custom-components/ble_monitor/assets/77659586/4f183f69-e746-4f01-8d7a-939ac4e40803">
<img width="565" alt="65796434c5383fb2f5cbcbb1c86acb8" src="https://github.com/custom-components/ble_monitor/assets/77659586/f1fc8148-abb5-40a6-999f-8e406927281a">

### Sensor type

XMWXKG01LM

**Comment by Ernst79** [comment]
This is by design, as the sensor does not send “no press”. BLE monitor will let the state return to no press after 40 seconds, by default, but you can change that in the ble monitor settings. The last press attribute will not return to no press, to allow users to make automations (e.g. if last press attribute is single press for 20 minutes, then do something).

**Comment by w961471797** [comment]
Many thanks
