### ISSUE TITLE
[New Sensor]: SkyRC MC3000 Battery Charger

### ISSUE THREAD

**Issue by Gaudi111** [custom-components/ble_monitor#1360]
### Sensor Description

SkyRC MC3000 Battery Charger

### Additional information

I would like to have added to the sensors repository the [SkyRC MC3000 Battery Charger](https://www.skyrc.com/MC3000_Charger).
It can communicate with other devices using BLE. 
It will be great if the charger could be added so charging data for cell can be automatically logged by Home Assistant without having to resort to a computer, phone or direct connection.

Currently some other users have come up with Python modules to communicate and decode the information, which may probe useful to work out the integration:

[Simple application for monitoring SkyRC MC3000 charger over BLE/Bluetooth and for export/import of profiles over USB @ GitHub](https://github.com/kolinger/skyrc-mc3000)

[Control SkyRC MC3000 battery chargers via BLE. @PyPi](https://pypi.org/project/skyrc-ble/)

### BLE advertisements

```shell
Information included in above mentioned GitHub repo.

    SERVICE_UUID = "0000ffe0-0000-1000-8000-00805f9b34fb"
    CHARACTERISTIC_UUID = "0000ffe1-0000-1000-8000-00805f9b34fb"
```

**Comment by myhomeiot** [comment]
Unfortunately this sensor requires active connection in order to get data and send commands, so it's can't be implemented in Passive BLE Monitor. But this can be implemented as Home Assistant Bluetooth device [integration](https://developers.home-assistant.io/docs/bluetooth) or as ESPHome component or as ESPHome sensors based on data received using [BLE Client](https://esphome.io/components/ble_client.html) component.

**Comment by BreitiDE** [comment]
h, had someone realized to add MC3000 to HA by ESPhome, addon or other methode ?
