### ISSUE TITLE
Use binary sensors

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#166]
**Problem description**
Follow up of discussion in #159

MCCQ02HL and WX08ZM sensors are currently discovered as `sensors` with on/off state. However, these sensors are actually `binary_sensors`, not `sensors`. This causes that the sensors are only able to show `on/off` and not e.g. `closed/open`. 

**(Possible) Solution**
This issue is to discuss how to solve this. The final goal should be that binary sensors are discovered with the proper device class, and show their appropriate state. 

Proposal for device classes
MCCQ02HL --> `open/close` (DEVICE_CLASS: opening)
MCCQ02HL --> `light/dark` (DEVICE_CLASS: light)
WX08ZM  --> `power detected/no power` (DEVICE_CLASS: power)

**To Do**

To achieve this, we should 

- [x] move the monitoring to `__init__.py` (integration level)
- [x] keep the add_enties in `sensor.py` and `binary_sensor.py` at platform level)
- [x] move BLE ADV parser to HCIdump thread because this is the only way we can sort messages (see next task)
- [x] split the incoming messages into two separate queues (one for each platform)?
- [x] move the `SwitchingSensors` to `binary_sensor.py`

**Findings of other examples that could help**
I think the [smarty](https://github.com/home-assistant/core/tree/dev/homeassistant/components/smarty) can be used as an base example, although it has part of the code in a pypi package (pysmarty). 

What I found in the smarty component, is that there are two links between `__init__.py` and e.g. `sensor.py`
Data
- in `__init__.py`, data is collected in `smarty` and this is passed to `hass.data[DOMAIN]`
```
    smarty = Smarty(host=host)
    hass.data[DOMAIN] = {"api": smarty, "name": name}
```
- in `sensor.py` it gets the data via `smarty = hass.data[DOMAIN]["api"]`

Updating
- It uses `dispatcher_send(hass, SIGNAL_UPDATE_SMARTY)` in `__init__.py` after receiving data 
- In `sensor.py` it uses this in the entity. 

```
    async def async_added_to_hass(self):
        """Call to update."""
        async_dispatcher_connect(self.hass, SIGNAL_UPDATE_SMARTY, self._update_callback)

    @callback
    def _update_callback(self):
        """Call update method."""
        self.async_schedule_update_ha_state(True)
```

Not entirely sure how this update link exactly works.

**Comment by Magalex2x14** [comment]
@Ernst79 , Thanks for putting everything together and organizing it. This is exactly what I was talking about when I mentioned dispatchers earlier. We'll figure it out. We just need a little time to read and try...

So far, I see it this way: we are doing two queues for our platforms. We can link these queues to the platform using hass.data. The HCIdump thread scatters data into different queues depending on its type.
The platform has to create the appropriate entities and update them, and this has to happen continuously. In this regard, the question is - what will happen if we do not start executing the platform code in a loop as a separate thread, but simply when we put a message in the queue, we will give a signal to the corresponding dispatcher? What happens if such a signal arrives before the previous dispatcher exits? How do we make the `period` option work if we can no longer control the time in the loop? I already have some thoughts, actually, but I still have to think it over.

**Comment by Magalex2x14** [comment]
@Ernst79 the first steps have been taken. I'll be offline this afternoon.
Until we moved on, if you have a free minute, test the branch `magalex_experiments`?
I planned to try different little things, but in the end, I came to a solution ) Everything turned out to be easier, it seemed at first, I don't know why I didn't see it right away... And no dispatchers. Everything works for me.

**Comment by Ernst79** [comment]
Whow, that was fast. I’ll try in an hour.

**Comment by Magalex2x14** [comment]
One more step has been taken. I continue in the binary_sensors branch

**Comment by Magalex2x14** [comment]
OK. Seems like all good.

![image](https://user-images.githubusercontent.com/4982025/100255975-3bfb9080-2f55-11eb-9de4-f998a80cc9bd.png)

Perhaps a little not optimal (especially in the part concerning the distribution of messages to queues. All cards were confused by the need to send information about the battery to binary_sensors), but quite decent, as it seems to me. Moreover, after transferring the parser to the HCIdump stream, the load on the processor noticeably decreased.

Today I will watch, and if all is well, then it will be possible to publish a new beta. @Ernst79, I ask you to check if everything is good in the part concerning measuring sensors.

**Comment by Magalex2x14** [comment]
![image](https://user-images.githubusercontent.com/4982025/100259386-34d68180-2f59-11eb-89df-784cddc9d500.png)

**Comment by Ernst79** [comment]
I will check tonight for the normal sensors. Can you explain the difference in CPU usage? Just out of curiosity.

**Comment by Magalex2x14** [comment]
I think that the decrease is due to the fact that earlier all received messages were queued, without dropping duplicates, and without other preprocessing. And now only meaningful data get into the platform.

In addition, in binary_sensors, I made a small change to aioblescan_ext, which played a role in this (there was "unpacking" for each of the HCI-events, despite the fact that this is only required at the time of initialization - I fixed that).

Since I have three BT-interfaces, I get about 5000 HCI-events per minute. Perhaps, on simpler installations, the difference will not be so obvious ...

**Comment by Ernst79** [comment]
Three BT interfaces, whoaw. But it is all working fine. Nice job!

**Comment by Magalex2x14** [comment]
I caught the error at night:

```
2020-11-26 01:19:31 ERROR (Thread-7) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/sensor.py", line 148, in run
    sensors[b_i].collect(data)
IndexError: list index out of range
```

Based on the timing, this is the MCCGQ02HL battery. I am engaged - there will be a fix.

**Comment by Magalex2x14** [comment]
Fixed. The battery in binary sensors complicates things a little)

**Comment by andrewjswan** [comment]
I try 0.8.4-beta and all work excellent :) thanks!
But i have some idea:
- Recovering the state after the start is now working for all types of sensors, whether it is possible to make a separate option to recover the values of the battery state, the state of conventional sensors and the state of binary sensors (I am not sure that this is necessary at all).
- Can I add the ability to change the device class in settings for the opening sensor? I.e. door (DEVICE_CLASS: door), garage (DEVICE_CLASS: garage_door), window (DEVICE_CLASS: window)? Let it be as it is by default (DEVICE_CLASS: opening).

**Comment by Magalex2x14** [comment]
[HA allows you to change the device class.](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui)
![image](https://user-images.githubusercontent.com/4982025/100434131-197c8b00-30ad-11eb-8301-8a9124440af2.png)

**Comment by andrewjswan** [comment]
@Magalex2x14 I agree, I missed this moment from attention.

**Comment by Magalex2x14** [comment]
> Recovering the state after the start is now working for all types of sensors, whether it is possible to make a separate option to recover the values of the battery state, the state of conventional sensors and the state of binary sensors (I am not sure that this is necessary at all).

Please make this as a separate issue. I agree it's worth doing. Or maybe a separate option per device...

**Comment by andrewjswan** [comment]
> Please make this as a separate issue.

Request done - https://github.com/custom-components/ble_monitor/issues/176 :)
