### ISSUE TITLE
Duplicated devices

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#192]
I noticed that all devices were duplicated, how to delete those without a battery indicator?  I'm using the latest beta.
![Screenshot_2020-12-09-07-24-51-807_io homeassistant companion android](https://user-images.githubusercontent.com/3609660/101588796-d648e300-39ef-11eb-99c9-3c13c17fd51b.jpg)

**Comment by Magalex2x14** [comment]
Do you deleted configuration from configuration.yaml?

**Comment by Ernst79** [comment]
I’ve written a section for deleting old entities and devices in the [readme](https://github.com/custom-components/ble_monitor/tree/config_flow_restored#deleting-devices-and-sensors) . Duplication of devices will be fixed in the following beta, although it might happens once more when updating from beta to beta. Sorry about that.

In short, entities can be deleted after a restart. Devices can be deleted with a service.

**Comment by andrewjswan** [comment]
> Do you deleted configuration from configuration.yaml?

No, i simply update integration ... I need delete configuration from configuration.yaml?

**Comment by andrewjswan** [comment]
> In short, entities can be deleted after a restart. Devices can be deleted with a service.

I have only duplicated devices, and not have duplicated entities

**Comment by Ernst79** [comment]
One of the devices will only have entities that are unavailable (after a restart of HA). Delete these entities first if still there. When there are no more entities for that device, go to developer tools --> services and find the following service in the drop down menu (`ble_monitor.cleanup_entries`) and click `call service`

![image](https://user-images.githubusercontent.com/24375847/101618640-8b8c9280-3a12-11eb-803f-781d61b8b61f.png)

**Comment by andrewjswan** [comment]
> Devices can be deleted with a service

I run ble_monitor.cleanup_entries and duplicated devices deleted :) Thanks!

**Comment by Ernst79** [comment]
As said, the issue with duplicate devices will be fixed in the next beta (0.9.3).
