### ISSUE TITLE
Retain last value

### ISSUE THREAD

**Issue by flouck** [custom-components/ble_monitor#194]
First of all, thank you for this great custom component!

I have got one BLE temp sensor which is slightly too far from my Raspberry. So from time to time, it losts its connection and Lovelace displays N/A as a value.

I would love to see the last retained value instead. Maybe enabling this as an option in the yaml config. What do you think?
That would be very useful for me as I use this sensor in a cliamte generic thermostat. This climate entity stops heating when not receiving any temperature value.

![image](https://user-images.githubusercontent.com/60158607/102015419-ccaadc80-3d5b-11eb-9dc6-82038a8083af.png)

**Comment by Magalex2x14** [comment]
@flouck this option is already implemented in the component and [described](https://github.com/custom-components/ble_monitor#restore_state) in the documentation.

In addition, recently on the forum we [discussed](https://community.home-assistant.io/t/passive-ble-monitor-integration-xiaomi-mijia-ble-mibeacon-monitor/177352/663?u=magalex) methods for improving reception. Read it, you can find something acceptable for yourself. Our FAQ also contains some useful information [on this subject](https://github.com/custom-components/ble_monitor/blob/master/faq.md#reception-issues).

**Comment by flouck** [comment]
Hi @Magalex2x14 , thank you for your quick reply.
`restaore_state` has always been to `True` on my side. However, it seems that it is useul for HA restart, not for connection loss. Or is it? 

For improving reception, I guess an external bluetooth gateway would be better. As I have the Qingping one and I see there is an issue related, I will wait for that. Thank you however for all your advices.

**Comment by Magalex2x14** [comment]
Hmmm. Yes, you're right, this option works at the time of HA reboot. The main thing here is that at the time of the reboot, the sensor entity must have a value different from N/A.

 But do you mean that you get N/A state without rebooting? I won't believe it until I see it myself :)
This is something strange since our component does not operate with connections to sensors, it just listens to the broadcast and updates the status when messages arrive. If there are no messages for a long time, then the only thing that indicates this is the time since the last update of the sensor, the component does not implement any timeout logic. I also have a sensor with unstable reception, located on the border of "audibility":
<img src="https://user-images.githubusercontent.com/4982025/102016954-ca08b100-3d74-11eb-8e48-5691866b6db4.png" alt="" width="30%" height="30%">
You should clarify why you see the N/A status at the sensor. It is better to look at the properties of the entity since the N/A state in Lovelace can be displayed the same for two states: `unknown` and `unavailable`. There is a difference.

**Comment by flouck** [comment]
Hi!
It is `unavailable`
Just took this screenshot. No recent reboot though.
![image](https://user-images.githubusercontent.com/60158607/102090735-1d830980-3e1e-11eb-986d-f936bfa05ddd.png)

**Comment by Magalex2x14** [comment]
What's in HA log? Are there any errors?
In addition, if you have a 0.9.x branch (beta at the moment), then when you apply changes to the integration settings in the UI, the component is also reloaded.

**Comment by Ernst79** [comment]
@flouck Any update on this issue. Are you still facing this issue with the 0.9.x branch? Otherwise, please close the issue.

**Comment by flouck** [comment]
I think we can close it for now. I will open it if it happens again.
