### ISSUE TITLE
As of Home Assistant 2021.6, this integration will no longer be loaded

### ISSUE THREAD

**Issue by rchovan** [custom-components/ble_monitor#324]
Hi, 
there is new warning message in HA logs:
```
Logger: homeassistant.loader
Source: loader.py:786
First occurred: 7:16:48 PM (1 occurrences)
Last logged: 7:16:48 PM
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'mitemp_bt'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'mitemp_bt'
```

**Comment by bentolor** [comment]
I get the same for the `ble_monitor` component. I have installed it with the [manual installation method](https://github.com/custom-components/ble_monitor#2-install-the-custom-integration)

**Comment by Ernst79** [comment]
@rchovan, This is an error from `mitemp_bt`. Our component has been renamed a long time ago to `ble_monitor`. Please remove the `mitemp_bt` folder and install `ble_monitor`

@bentolor You probably have an old version. It won't be updated, because you installed it manually. I suggest to start using HACS, as this will keep track of updates. However, if you want to stay with the manual installation method, an update with the latest version should fix your problem.

**Comment by Ernst79** [comment]
I'm closing this issue. See the above post for the solution (in short delete `mitemp_bt` and install the latest version of `ble_monitor`)

If you still have issues, feel free to reopen the issue.

**Comment by bentolor** [comment]
@Ernst79 Thanks for your support! In my case indeed my fault. I updated last on Apr. 5 and missed that the fixed arrived after.

I moved aways from HACS as it cause _huuuuge_ delays in startup and I had no relevant amount of custom components up to date.
