### ISSUE TITLE
Can't open HCI socket.: Address family not supported by protocol

### ISSUE THREAD

**Issue by pilot1981** [custom-components/ble_monitor#387]
Hi,
when I go to launch Check Home Assistant configuration add-on before upgrade from core-2021.5.5 to core-2021.6.0 I obtain this entry in logs:

Can't open HCI socket.: Address family not supported by protocol

wht means? it's related to use bluetooth interface form ble_monitor component?

regards

**Comment by Ernst79** [comment]
I checked it myself, no errors found. 

![image](https://user-images.githubusercontent.com/24375847/120681973-39499d00-c49c-11eb-92be-6adb4d7f6cbc.png)

What kind of system do you use? Home Assistant Os?

**Comment by pilot1981** [comment]
Raspberry po 3+ With HASSIO

DV

**Comment by Ernst79** [comment]
It looks related to not having Bluetooth properly installed. 

I think a first step is to restart the full system (not only HA). It might be that after an earlier update of Home Assistant OS , something isn’t loaded correctly. After the full restart, try it again.

**Comment by pilot1981** [comment]
very strange..bluetooth interface seems to work fine...ble_monitor find all my bluetooth devices:
![image](https://user-images.githubusercontent.com/46350465/120757734-3937b480-c511-11eb-9d64-65bbbfb479fd.png)
now I try to restart and check it again...

**Comment by Ernst79** [comment]
very likely to be an aesthetic problem, I think this config check is setting up a virtual new HA installation, which might not have the right root access to the hci interface. In the past we had another very similar error, which I moved from an Error to a Warning, to make it pass this test. In that case, it was working fine after updating, but I can understand you want to be sure before you update.

As said, I think the "problem" is because the test doesn't have root access to your hci interface (= Bluetooth radio). It might need to be fixed in the config check add in. 

If it still fails, could you copy the full error message, including the type of Error (Error or Warning).

**Comment by pilot1981** [comment]
after restart of HA, I tried again...error come back...


now I try to update to 2021.6.1...

**Comment by Ernst79** [comment]
Did it work?

**Comment by pilot1981** [comment]
I already updated and all seems to work fine!

thanks
