### ISSUE TITLE
Add Support for Xiaomi Mijia Mosquito Repellent 2 (WX10ZM)

### ISSUE THREAD

**Issue by happyme531** [custom-components/ble_monitor#407]
The device is extremely similar to the Xiaomi Mijia Mosquito Repellent (WX08ZM), But it support USB Type-C powering and Bluetooth Mesh control.  

There is probably a bug with report_unknown function. I see no further log output even set the report_unknown level to Others.   
Everything else works fine.   
Here is the log:  

```
2021-06-15 23:18:47 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for Other sensors, be ready for a huge output...
2021-06-15 23:18:47 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.ble_monitor
2021-06-15 23:18:47 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.ble_monitor
```
And it shows nothing more.

This is the result of hcidump `hcidump --raw -i hci1 hci > hcidump.log`.
[hcidump.log](https://github.com/custom-components/ble_monitor/files/6656893/hcidump.log)

**Comment by Ernst79** [comment]
I've analysed your data. 

I see one type of message (multiple times) that comes from an unknown Xiaomi device (it has 1695FE in it, which is a trigger for Xiaomi devices). Second line is another Xiaomi device for comparison)

```
-----------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD  Xiaomi Frame Product Frame ------MAC--------   -----PAYLOAD-------------  RSSI
type code    evt rep type addr                             flag         type  UUID   ctrl   ID    cnt                      
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 04   3E 20  02  01   00   00  F3 E3 8D ED 60 B4   14  02   01  06  10   16  95 FE  90 55  40 10   01   F3 E3 8D ED 60 B4   0E 00                       CD   WX10ZM
 04   3E 27  02  01   00   00  AB 0B 0D 38 C1 A4   1B  02   01  06  0F   16  95 FE  30 5A  11 07   01   AB 0B 0D 38 C1 A4   08 07 09 50 54 48 2D 33 4D  B2   PTH-3M
```

This message is ignored by BLE monitor because it is in Xiaomi's Bluetooth Mesh format (you can only see that when you enable logging in HA at debug level), that is only why you didn't see any data if you had used `report_unknonw: "Xiaomi"`. 

This mesh type flag is found from the `90 55` bytes, but that is too much detail. This Bluetooth Mesh format seems to be something new, I think it requires setting up a connection, but I have to investigate. I also did find one other message with the same MAC address, but no Xiaomi flag. The AD type indicates that this is "Mesh Beacon", following the "Mesh Profile Specification Section 3.9"

```
------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Val Len  AD  ---------------------------- PAYLOAD-------------------------------  RSSI
type code    evt rep type addr                             type                    
------------------------------------------------------------------------------------------------------------------------------------------
04   3E 24  02  01   03   00  F3 E3 8D ED 60 B4    18  17   2B  01  00 F6 4E 96 A3 23 D8 7E B6 00 00 00 00 B9 86 07 C0 6C 0C 51 8C    CC
```

So, very interesting, but I'll have to dig into this new? [Xiaomi Mesh standard](https://iot.mi.com/new/doc/embedded-development/ble/overview). (Use google translate for that page).

**Comment by rezmus** [comment]
ble mesh is much more complicated and a lot more going in during bind/auth/encryption. not sure if was reverse engineered already, but best option atm is to use mijia v3 hub (with ble mesh gateway) and this integration

https://github.com/AlexxIT/XiaomiGateway3

**Comment by Ernst79** [comment]
Yes, seems to be the best way to go. BLE monitor hasn't implemented authentication/binding to any device, as it is only listening passively. There are no plans to implement that.

**Comment by Ernst79** [comment]
Closing this issue, as Xiaomi Mesh isn't supported, due to its requirements to connect to the device, which is out of the scope of BLE monitor
