### ISSUE TITLE
Battery Drain SJWS01LM - Xiaomi Smart Water Leak Sensor

### ISSUE THREAD

**Issue by XxCabbyoO** [custom-components/ble_monitor#444]
Hi, with SJWS01LM - Xiaomi Smart Water Leak Sensor i have fast battery drain :(

![1626632209368](https://user-images.githubusercontent.com/65039581/126078142-98c913cd-3efc-4595-8c19-674206d07731.jpg)

new batteries drain within a few hours
I tried it a few months ago, so it's not because of a recent version. It also occurred back then

**Comment by Ernst79** [comment]
BLE monitor isn't connecting to the water leakage sensor, so it can't cause a battery drain by itself.

It can however be the case that BLE monitor isn't reporting back the right battery level. Could you check the battery level in MiHome app, to see if it matches BLE monitor?

**Comment by XxCabbyoO** [comment]
thanks for quick reply. the sensor was also really off after a few hours. had hoped that lasts longer than a day ;)

**Comment by Ernst79** [comment]
I think @andrewjswan has one, he often responses to messages.

**Comment by andrewjswan** [comment]
I have 3 sensors, and not have problem :)
![IMG_20210719_063624](https://user-images.githubusercontent.com/3609660/126099355-b4285294-f0a7-45ab-b6a9-1d2e82573f2a.jpg)
PS: In all sensors stock battery

**Comment by XxCabbyoO** [comment]
> 
> 
> I have 3 sensors, and not have problem :)
> ![IMG_20210719_063624](https://user-images.githubusercontent.com/3609660/126099355-b4285294-f0a7-45ab-b6a9-1d2e82573f2a.jpg)
> PS: In all sensors stock battery

Which BLE Gateway are you using? Using builtin Pi4 BLE

**Comment by andrewjswan** [comment]
@XxCabbyoO I use RPI 3B+ and Intel NUC ... with build in BT ...

**Comment by XxCabbyoO** [comment]
ok, thanks. Then unfortunately I do not know how to fix my battery drain. Since it can not be due to the ble monitor I close

**Comment by Magalex2x14** [comment]
The only case where ble_monitor can cause an increase in sensor power consumption is when the `Active scan` option is enabled. @XxCabbyoO make sure it is turned off.

**Comment by XxCabbyoO** [comment]
thank you, but the active scan function was/is disabled

**Comment by Ernst79** [comment]
Device tracker doesn't affect battery either. BLE monitor is only listening to ble advertisemetns, with the specified MAC, it is not asking the device to send data.

**Comment by andrewjswan** [comment]
> Then unfortunately I do not know how to fix my battery drain

Try change it to new ...

**Comment by iobu** [comment]
I have a similar problem with "Xiaomi Mi Water Leak Sensor" on Bluetooth and not Zigbee, battery CR2032 is drained in couple of days (maximum 20 days). Tried to make a workaround to this situation, but even with the 18650 battery is not able to stray alive more than 30 days. These sensors saved my house twice (so i will not speak badly of them), as an alternative the Aqara ones should be my next buy, because are on Zigbee and recognized by the same MiHome application. Please be advived and stay way from these sensors on Bluetooth.  
![IMG20220803180215](https://user-images.githubusercontent.com/97037487/201514083-cf9e750f-88b1-4804-966d-fa8d6b62ebaa.jpg)
![IMG20220803164828](https://user-images.githubusercontent.com/97037487/201514090-d7c05450-fb01-44e6-a574-852c091a4987.jpg)
![IMG20220803161814](https://user-images.githubusercontent.com/97037487/201514099-eab3831a-d560-4d78-908d-8f8602ce6c2f.jpg)
![MiWaterLeakSensor](https://user-images.githubusercontent.com/97037487/201514145-27552ed5-5c06-4a20-8b72-36f9cb8a42ed.jpg)

**Comment by IamMattM** [comment]
> I have a similar problem with "Xiaomi Mi Water Leak Sensor" on Bluetooth and not on Zigbee, battery CR2032 is drained in couple of days (maximum 20 days). Tried to make a workaround to this situation, but even with the 18650 battery is not able to stray alive more than 30 days. These sensors saved my house twice (so i will not speak badly of them), as an alternative the Aqara ones should be my next buy, because are on Zigbee and recognized by the same MiHome application. Please be advised and stay away from these sensors on Bluetooth. ![IMG20220803180215](https://user-images.githubusercontent.com/97037487/201514083-cf9e750f-88b1-4804-966d-fa8d6b62ebaa.jpg) ![IMG20220803164828](https://user-images.githubusercontent.com/97037487/201514090-d7c05450-fb01-44e6-a574-852c091a4987.jpg) ![IMG20220803161814](https://user-images.githubusercontent.com/97037487/201514099-eab3831a-d560-4d78-908d-8f8602ce6c2f.jpg) ![MiWaterLeakSensor](https://user-images.githubusercontent.com/97037487/201514145-27552ed5-5c06-4a20-8b72-36f9cb8a42ed.jpg)

Could I ask how you managed to disassemble the sensor to get access to the PCB ?
One of my sensor switch is not longer responding ad I would like to see if I can perhaps revive the unit.

Did you have to heat up the device to loosen up any glue ?
![image](https://user-images.githubusercontent.com/29542928/236550381-42dbf853-0b4d-49e7-af5c-7d063b5f884b.png)

**Comment by IamMattM** [comment]
Actually managed to push the PCB towards the plastic housing and can now click onto button once more. 

Still would be interested to know how you got inside the device without damaging it...

**Comment by iobu** [comment]
Hi @IamMattM,
Please do not heat the surface of the sensor in any way because the plastic is made of PETG (plastic bottles) and will melt immediately. Instead, use a straight screwdriver to insert slowly between the walls of the case (you have to turn the sensor face down). Unfortunately, the two sensor housings are glued together and anyway you will damage the plastic and it will certainly not remain intact in its original form. If you look carefully at the pictures I posted, you will notice straight traces of the screwdriver on the edge of the sensor housing.


![screwdriver1](https://user-images.githubusercontent.com/97037487/237021475-a40274ff-7377-4f40-9988-991728f1b368.jpg)
![screwdriver2](https://user-images.githubusercontent.com/97037487/237021470-6f9f124d-d946-4200-8c3a-3bfba6a2854e.jpg)

**Comment by iobu** [comment]
Hi @IamMattM,

I forgot to mention that the new Zigbee (Aqara) sensors no longer report the battery level. If this is a problem for you, maybe you should still try another version of sensors from Xiomi, also on Bluetooth.

**Comment by IamMattM** [comment]
> Hi @IamMattM,
> 
> I forgot to mention that the new Zigbee (Aqara) sensors no longer report the battery level. If this is a problem for you, maybe you should still try another version of sensors from Xiaomi, also on Bluetooth.

Thanks. I'll bear this in mind.

I would go for <SJCGQ11LM> which seems to be able to report battery through Zigbee2MQTT according to this post:

![image](https://github.com/custom-components/ble_monitor/assets/29542928/8d363444-303e-4edf-a026-8d34337e0626)
>
