### ISSUE TITLE
RuuviTags not working with 4.4.0

### ISSUE THREAD

**Issue by La-te** [custom-components/ble_monitor#457]
I'm having ble_monitor installed through HACS and did an upgrade from 4.3.1 to 4.4.0. After the upgrade and reboot RuuviTags were not updating anymore but LYWSDCGQ seemed to work fine. Should RuuviTags still work?

I did try another reboot but it didn't help. I did a quick look at the logs but that did't immediately reveal a relevant issue if I even looked at the right place. Before further investigation I just went back to 4.3.1 and everything seems to be working. I'm running latest Home Assistant on Raspberry Pi 4. Before further investigation I would like to know are the RuuviTags working for someone on 4.4.0.

**Comment by Ernst79** [comment]
I scanned through my changes, but cannot find a reason why it isn't working anymore immediately. Could you tell me which firmware version you have on the RuuviTags?

**Comment by La-te** [comment]
Most of them are on official V5 and some running the beta branch. However, neither did show any values on the dashboards. Maybe I'll give it another try and look into more details.

**Comment by Ernst79** [comment]
I think I found the issue, the ble_parser is initiated again on each new advertisement, causing to start with an empty the list of packet_ids. Due to the filtering of unique packet_ids, it was ignoring all advertisements, as it will also ignore the very first advertisement. I need to do some checks, but I hope to finish a fix today.

**Comment by Ernst79** [comment]
Fixed in 4.4.1
