### ISSUE TITLE
Documentation Error in section about adding devices

### ISSUE THREAD

**Issue by backcountrymountains** [custom-components/ble_monitor#522]
In the [adding devices section](https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation) there is a code snippet for using hcidump:
```sudo hcidump --raw hci > dump.txt```
I think it should specify ```hci0``` as the other examples do:
```sudo hcidump --raw hci0 > dump.txt```

no biggie

**Comment by Thrilleratplay** [comment]
@backcountrymountains I can see where you may think that, and I have made this same mistake too. The other command examples such as `hciconfig` specify `hci0` because that is the device name.  If you have more than one Bluetooth adpater, you may need to use `hci1`.  `hcidump` is a little different because `hci` is the type of packets it is filtering.  [From the hcidump man page](https://linux.die.net/man/8/hcidump)  

> filter is a space-separated list of packet categories: available categories are lmp, hci, sco, l2cap, rfcomm, sdp, bnep, cmtp, hidp, hcrp, avdtp, avctp, obex, capi and ppp. If filters are used, only packets belonging to the specified categories are dumped. By default, all packets are dumped.

**Comment by backcountrymountains** [comment]
Point taken. I'm using an RPI Zero W and I didn't get any output from 
```sudo hcidump --raw hci > dump.txt``` when I first tried it but after messing around and trying ```sudo hcidump --raw hci0 > dump.txt``` I did get an ouput. Looks like that was just a coincidence. Closing as RTFM
