### ISSUE TITLE
Active scan per device

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#650]
Request for the forum https://community.home-assistant.io/t/passive-ble-monitor-integration/303583/328

After reading the documentation, I understand that the passive/active scan option is defined at the integration level. Isn’t it possible to define this option at the device level in order to actively poll the devices with a very low transmission rate, while keeping the passive listening option for devices that send updates 20x / min ? I don’t want to increase the power consumption of all my bluetooth sensors just for one slow sensor.

**Comment by Magalex2x14** [comment]
Unfortunately, no, this is not possible, since the active scan function is activated when a scan is requested to the controller, in other words, this is a property of the scanning process itself, and active scan requests are broadcast in nature. That is, the only thing we can theoretically do is turn it on for one period and turn it off for another.

**Comment by Magalex2x14** [comment]
Or we can activate it on a per BT adapter basis.

**Comment by Ernst79** [comment]
I would then leave it as it is. I thing the "added value" is too limited.

**Comment by Magalex2x14** [comment]
Yes I agree.
