### ISSUE TITLE
problem with Qingping CGPR1 motion sensor, motion detection skipped

### ISSUE THREAD

**Issue by shift-del1** [custom-components/ble_monitor#873]
Firmware: Xiaomi (MiBeacon V5 encrypted), timeout is 25 seconds in Mi Home
HA: OS 8.1, Core 2022.5.5, integration: 8.6.6

While in Mi Home all motions are detected, in HA some of them are skipped. According to the Mi Home log, the device detects motion, but the HA integration does not transfer this information from the sensor to HA. See one at 9:21:23:

![Screenshot_2022-05-27-09-22-31-774_com xiaomi smarthome](https://user-images.githubusercontent.com/63366470/170659306-eb7f9b93-b23f-4e56-92b7-cb06c5c088ee.jpg)

The same in HA:

![Screenshot_2022-05-27-09-23-09-693_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/170659577-ede06fa8-e348-454e-86b2-44573ea41f4c.jpg)

Can you please check what could be the issue?

**Comment by shift-del1** [comment]
Hell Ernst79,
The motion sensor is working in "dual mode", I prefer BLE monitor because of its passive behavior, but I kept Mi Home mode as a backup in case of an issue. HA is running on a NAS, so the USB extension cable is already in place to keep the dongle as far from the NAS as possible.The distance between the dongle and the motion sensor is roughly 30-40cm, so shouldn't be a problem. The integration from AlexxIT is also available, but BT devices are not enabled to be transferred to HA, so gateway only exposes them to Mi Home. Maybe the solution will be to switch to a Zigbee motion sensor, where the timeout is configurable, like the Aqara P1. Anyway, thanks for checking my issue, I appreciate your help and work.

**Comment by Ernst79** [comment]
Sound like you should have a good reception yes, I agree. The only way to find out if the problem is with BLE monitor is to enable debug logging for BLE monitor in HA and enable report unknown for this MAC address (check the FAQ how to do this) and check the incoming BLE advertisements. Compare the messages from the report unknown function with the incoming "processed" messages, each BLE advertisement should be translated to a "processed" message. With "processed" message, I mean something like {motion: 1, "light": 0, battery: 100, mac: AABBCCAABBCC} etc. 

Unfortunately this is some debugging you have to do yourself.
